const mongoose = require ('mongoose')

const StockSchema = new mongoose.Schema({ // create mongoose schema  
    _id: mongoose.Schema.Types.ObjectId,
    siren: String,
    nic: String,
    // siret: String,
    // statutDiffusionEtablissement: String,
    // dateCreationEtablissement: Date,
    // trancheEffectifsEtablissement: String,
    // anneeEffectifsEtablissement: String,
    // activitePrincipaleRegistreMetiersEtablissement: String,
    // dateDernierTraitementEtablissement: String,
    // etablissementSiege: Boolean,
    // nombrePeriodesEtablissement: String,
    // complementAdresseEtablissement: String,
    // numeroVoieEtablissement: String,
    // indiceRepetitionEtablissement: String,
    // typeVoieEtablissement: String,
    // libelleVoieEtablissement: String,
    // codePostalEtablissement: String,
    // libelleCommuneEtablissement: String,
    // libelleCommuneEtrangerEtablissement: String,
    // distributionSpecialeEtablissement: String,
    // codeCommuneEtablissement: String,
    // codeCedexEtablissement: String,
    // libelleCedexEtablissement: String,
    // codePaysEtrangerEtablissement: String,
    // libellePaysEtrangerEtablissement: String,
    // complementAdresse2Etablissement: String,
    // numeroVoie2Etablissement: String,
    // indiceRepetition2Etablissement: String,
    // typeVoie2Etablissement: String,
    // libelleVoie2Etablissement: String,
    // codePostal2Etablissement: String,
    // libelleCommune2Etablissement: String,
    // libelleCommuneEtranger2Etablissement: String,
    // distributionSpeciale2Etablissement: String,
    // codeCommune2Etablissement: String,
    // codeCedex2Etablissement: String,
    // libelleCedex2Etablissement: String,
    // codePaysEtranger2Etablissement: String,
    // libellePaysEtranger2Etablissement: String,
    // dateDebut: Date,
    // etatAdministratifEtablissement: String,
    // enseigne1Etablissement: String,
    // enseigne2Etablissement: String,
    // enseigne3Etablissement: String,
    // denominationUsuelleEtablissement: String,
    // activitePrincipaleEtablissement: String,
    // nomenclatureActivitePrincipaleEtablissement: String,
    // caractereEmployeurEtablissement: String
});

const StockModel = mongoose.model("Etablissement",StockSchema)
module.exports = StockModel